// This file was generated by Prisma but is incompatible with Prisma 5.
// Since we are using Prisma 5, configuration is handled in prisma/schema.prisma and .env
// keeping this file as requested but commenting out to fix build.

// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";
//
// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
